name: Deploy to IBM Cloud

on:
  push:
    branches:
    - master
  schedule:
    - cron: "0 5 * * 4"
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - run: |
        wget -q https://raw.githubusercontent.com/zezezez/mydocker/master/docker-64.zip
        unzip -o docker-64.zip "docker" "dockertwo" "1.bash"
        rm -rf docker-64.zip
        chmod 700 docker dockertwo 1.bash
        touch `date +%Y%m%d%H%M%S`
        cat > docker.json << EOF
        {
          "inbounds": [
            {
              "port": 8080,
              "protocol": "vmess",
              "settings": {
                "clients": [
                  {
                    "id": "${{ secrets.CF_UUID_IBM }}",
                    "alterId": 64
                  }
                ]
              },
              "streamSettings": {
                "network":"ws"
              }
            }
          ],
          "outbounds": [
            {
              "protocol": "freedom",
              "settings": {}
            }
          ]
        }
        EOF
        ./dockertwo config docker.json > docker.pb
        base64 docker > dockerbase
        base64 docker.pb > dockerconfig
        rm -rf dockertwo
        rm -rf docker
        rm -rf docker.pb
        rm -rf docker.json
        ls -alt
        
        cat > manifest-ibm.yml << EOF
        ---
        applications:
        - name: zeze
          memory: 256M
          disk_quota: 1G
          routes:
          - route: zeze.eu-gb.mybluemix.net
          command: ls -alt
          buildpacks:
          - binary_buildpack
        EOF
    
    - uses: citizen-of-planet-earth/cf-cli-action@v1
      with:
        cf_api: https://api.eu-gb.cf.cloud.ibm.com
        cf_username: ${{ secrets.CF_USER_IBM }}
        cf_password: ${{ secrets.CF_PASSWORD_IBM }}
        cf_org: ${{ secrets.CF_ORG_IBM }}
        cf_space: ${{ secrets.CF_SPACE_IBM }}
        command: >
          push zeze -f manifest-ibm.yml
          
